import { ProductCategory, type Product } from "@/lib/types";

export const categories: Array<{
  id: ProductCategory;
  label: string;
  description: string;
}> = [
  {
    id: ProductCategory.All,
    label: "All",
    description: "Everything fresh",
  },
  {
    id: ProductCategory.Fruits,
    label: "Fruits",
    description: "Seasonal picks",
  },
  {
    id: ProductCategory.Vegetables,
    label: "Vegetables",
    description: "Daily greens",
  },
  {
    id: ProductCategory.Dairy,
    label: "Dairy",
    description: "Milk and more",
  },
  {
    id: ProductCategory.Bakery,
    label: "Bakery",
    description: "Baked today",
  },
  {
    id: ProductCategory.Pantry,
    label: "Pantry",
    description: "Kitchen staples",
  },
];

export const products: Product[] = [
  {
    id: "pomegranate",
    name: "Ruby Pomegranate",
    category: ProductCategory.Fruits,
    price: 129,
    unit: "2 pcs",
    rating: 4.8,
    deliveryEta: "12 min",
    image: "/image.jpg",
    featured: true,
  },
  {
    id: "avocado",
    name: "Hass Avocado",
    category: ProductCategory.Fruits,
    price: 189,
    unit: "pack of 2",
    rating: 4.7,
    deliveryEta: "15 min",
    image: "/image.jpg",
  },
  {
    id: "spinach",
    name: "Baby Spinach",
    category: ProductCategory.Vegetables,
    price: 49,
    unit: "150 g",
    rating: 4.6,
    deliveryEta: "10 min",
    image: "/image.jpg",
    featured: true,
  },
  {
    id: "tomato",
    name: "Vine Tomatoes",
    category: ProductCategory.Vegetables,
    price: 39,
    unit: "500 g",
    rating: 4.5,
    deliveryEta: "9 min",
    image: "/image.jpg",
  },
  {
    id: "milk",
    name: "Farm Fresh Milk",
    category: ProductCategory.Dairy,
    price: 68,
    unit: "1 L",
    rating: 4.9,
    deliveryEta: "8 min",
    image: "/image.jpg",
    featured: true,
  },
  {
    id: "greek-yogurt",
    name: "Greek Yogurt",
    category: ProductCategory.Dairy,
    price: 115,
    unit: "400 g",
    rating: 4.7,
    deliveryEta: "14 min",
    image: "/image.jpg",
  },
  {
    id: "sourdough",
    name: "Sourdough Loaf",
    category: ProductCategory.Bakery,
    price: 149,
    unit: "1 loaf",
    rating: 4.8,
    deliveryEta: "18 min",
    image: "/image.jpg",
  },
  {
    id: "croissant",
    name: "Butter Croissant",
    category: ProductCategory.Bakery,
    price: 99,
    unit: "pack of 2",
    rating: 4.6,
    deliveryEta: "16 min",
    image: "/image.jpg",
  },
  {
    id: "basmati-rice",
    name: "Aged Basmati Rice",
    category: ProductCategory.Pantry,
    price: 249,
    unit: "1 kg",
    rating: 4.8,
    deliveryEta: "20 min",
    image: "/image.jpg",
  },
  {
    id: "olive-oil",
    name: "Extra Virgin Olive Oil",
    category: ProductCategory.Pantry,
    price: 399,
    unit: "500 ml",
    rating: 4.9,
    deliveryEta: "22 min",
    image: "/image.jpg",
  },
];
